### ISSUE TITLE
Duolingo changed element at the login

### ISSUE THREAD

**Issue by oxGorou** [kbdevs/AutoDuo#1]
```
gorouflex@Les-MacBook-Pro ~ % python3 /Users/gorouflex/Downloads/duo.py 
Starting browser 1...
Element not found. Retrying in 3 seconds...
Element not found. Retrying in 3 seconds...
Element not found. Retrying in 3 seconds...
Element not found. Retrying in 3 seconds...
Element not found. Retrying in 3 seconds...
Element not found. Retrying in 3 seconds...
Element not found. Retrying in 3 seconds...
Element not found. Retrying in 3 seconds...
Element not found. Retrying in 3 seconds...
Element not found. Retrying in 3 seconds...
Element not found. Retrying in 3 seconds...
Element not found. Retrying in 3 seconds...
Element not found. Retrying in 3 seconds...
Element not found. Retrying in 3 seconds...
Element not found. Retrying in 3 seconds...
Element not found. Retrying in 3 seconds...
Element not found. Retrying in 3 seconds...
^CTraceback (most recent call last):
  File "/Users/gorouflex/Downloads/duo.py", line 25, in <module>
    element = driver1.find_element(By.XPATH, '//*[@id="root"]/div[2]/div/div[2]/div/div[1]/div/div[2]')
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 738, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 344, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="root"]/div[2]/div/div[2]/div/div[1]/div/div[2]"}
  (Session info: chrome=117.0.5938.88); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
0   chromedriver                        0x000000010e5ece58 chromedriver + 5090904
1   chromedriver                        0x000000010e5e3bc3 chromedriver + 5053379
2   chromedriver                        0x000000010e17f527 chromedriver + 447783
3   chromedriver                        0x000000010e1ce339 chromedriver + 770873
4   chromedriver                        0x000000010e1ce4f1 chromedriver + 771313
5   chromedriver                        0x000000010e214304 chromedriver + 1057540
6   chromedriver                        0x000000010e1f568d chromedriver + 931469
7   chromedriver                        0x000000010e2116e1 chromedriver + 1046241
8   chromedriver                        0x000000010e1f5433 chromedriver + 930867
9   chromedriver                        0x000000010e1c0042 chromedriver + 712770
10  chromedriver                        0x000000010e1c126e chromedriver + 717422
11  chromedriver                        0x000000010e5ae3b9 chromedriver + 4834233
12  chromedriver                        0x000000010e5b355d chromedriver + 4855133
13  chromedriver                        0x000000010e5ba4f2 chromedriver + 4883698
14  chromedriver                        0x000000010e5b428d chromedriver + 4858509
15  chromedriver                        0x000000010e5860ec chromedriver + 4669676
16  chromedriver                        0x000000010e5d2c58 chromedriver + 4983896
17  chromedriver                        0x000000010e5d2e10 chromedriver + 4984336
18  chromedriver                        0x000000010e5e37fe chromedriver + 5052414
19  libsystem_pthread.dylib             0x00007ff809b55202 _pthread_start + 99
20  libsystem_pthread.dylib             0x00007ff809b50bab thread_start + 15


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/gorouflex/Downloads/duo.py", line 38, in <module>
    time.sleep(3)
KeyboardInterrupt
```

Please fix this thank you!

**Comment by oxGorou** [comment]
@kbdevs Also the TamperMonkey script still fine only the py script is not working as Duolingo changed thier login screen element

**Comment by kbdevs** [comment]
Due to the way I have it detect the buttons its really dependent on it being the exact same environment as when finding xpaths, window size, extensions etc so id recommend you to try finding your own
